carilion_dw.Database.sql
create.cmd
dbo.BinaryDim.Table.sql
dbo.CensusGeographicalAreaDim.Table.sql
dbo.CensusMeasureFact.Table.sql
dbo.CensusMeasureTypeDim.Table.sql
dbo.CensusSourceDim.Table.sql
dbo.Cube_Data_Types.View.sql
dbo.Cube_Dimensions.View.sql
dbo.Cube_Dimension_Type.View.sql
dbo.Cube_Hierarchies.View.sql
dbo.Cube_Levels.View.sql
dbo.Cube_Measures.View.sql
dbo.Cube_Measure_Aggregator.View.sql
dbo.Cube_Measure_Groups.View.sql
dbo.Cube_Measure_Group_vs_Dimensions.View.sql
dbo.Cube_Usage_Between_Dimensions_And_Facts.View.sql
dbo.Cube_Usage_Between_Dimensions_And_Facts__Excel_Compatible.View.sql
dbo.DateDim.Table.sql
dbo.DepartmentDim.Table.sql
dbo.DiagnosisBridge.Table.sql
dbo.DiagnosisFact.Table.sql
dbo.DiagnosisHierarchy.Table.sql
dbo.DiagnosisPresentOnAdmitDim.Table.sql
dbo.DiagnosisSourceDim.Table.sql
dbo.DM_Quality_Fact.Table.sql
dbo.DRGDim.Table.sql
dbo.DRGFact.Table.sql
dbo.DRGSeqDim.Table.sql
dbo.DRGTypeDim.Table.sql
dbo.EDVisitAcuityLevelDim.Table.sql
dbo.EDVisitDim.Table.sql
dbo.EDVisitDispositionDim.Table.sql
dbo.EDVisitFact.Table.sql
dbo.EDVisitFinancialClass.Table.sql
dbo.EDVisitMeansOfArrivalDim.Table.sql
dbo.EncounterBillingClassDim.Table.sql
dbo.EncounterDepartmentDim.Table.sql
dbo.EncounterDim.Table.sql
dbo.EncounterEncouterTypeDim.Table.sql
dbo.EncounterFact.Table.sql
dbo.EncounterLevelofCareDim.Table.sql
dbo.EncounterPatientStatusDim.Table.sql
dbo.EncounterProductLineDim.Table.sql
dbo.EncouterBaseClassDim.Table.sql
dbo.ExecSqlStatementsTableType.UserDefinedTableType.sql
dbo.InpatientAdmitSourceDim.Table.sql
dbo.InpatientAdmitTypeDim.Table.sql
dbo.InpatientDim.Table.sql
dbo.InpatientDischargeDestinationDim.Table.sql
dbo.InpatientDischargeDispositionDim.Table.sql
dbo.InpatientFact.Table.sql
dbo.InpatientPatientClassDim.Table.sql
dbo.LabComponentDim.Table.sql
dbo.LabComponentResultFact.Table.sql
dbo.LabComponentResultFactLabStatusDim.Table.sql
dbo.LabComponentResultFactResultFlagDim.Table.sql
dbo.LabComponentSubstrateDim.Table.sql
dbo.LabComponentTypeDim.Table.sql
dbo.LabDim.Table.sql
dbo.LabTestCancellationReasonDim.Table.sql
dbo.LabTestDim.Table.sql
dbo.LabTestFact.Table.sql
dbo.LabTestNameDim.Table.sql
dbo.LabTestOrderPriorityDim.Table.sql
dbo.LabTestOrderSourceTypeDim.Table.sql
dbo.LabTestOrderTypeDim.Table.sql
dbo.LabTestSpecimenSourceDim.Table.sql
dbo.LabTestSpecimenTypeDim.Table.sql
dbo.LabTestVerificationStatusDim.Table.sql
dbo.LDAP_Dim.Table.sql
dbo.LDAP_UserProvider_ReportingBridge.Table.sql
dbo.MeasureDim.Table.sql
dbo.MeasureGroupDim.Table.sql
dbo.MeasureMDFact.Table.sql
dbo.MeasureMLFact.Table.sql
dbo.MeasureQDFact.Table.sql
dbo.MeasureQLFact.Table.sql
dbo.MeasureSourceDim.Table.sql
dbo.MedicationAdministrationActionDim.Table.sql
dbo.MedicationAdministrationFact.Table.sql
dbo.MedicationAdministrationRouteDim.Table.sql
dbo.MedicationDEAClassDim.Table.sql
dbo.MedicationDim.Table.sql
dbo.MedicationFormDim.Table.sql
dbo.MedicationOrderCalculatedDoseUnitDim.Table.sql
dbo.MedicationOrderClassDim.Table.sql
dbo.MedicationOrderDim.Table.sql
dbo.MedicationOrderDoseUnitDim.Table.sql
dbo.MedicationOrderFact.Table.sql
dbo.MedicationOrderFrequencyDim.Table.sql
dbo.MedicationOrderModeDim.Table.sql
dbo.MedicationOrderPriorityDim.Table.sql
dbo.MedicationOrderQuantityUnitDim.Table.sql
dbo.MedicationOrderRouteDim.Table.sql
dbo.MedicationOrderSetSourceDim.Table.sql
dbo.MedicationOrderSourceDim.Table.sql
dbo.MedicationPharmacologicalClassDim.Table.sql
dbo.MedicationPharmacologicalSubclassDim.Table.sql
dbo.MedicationTherapeuticClassDim.Table.sql
dbo.OutpatientAdmitConfStatrusDim.Table.sql
dbo.OutpatientAppointmentConfirmationStatusDim.Table.sql
dbo.OutpatientAppointmentStatusDim.Table.sql
dbo.OutpatientCancellationReasonDim.Table.sql
dbo.OutpatientDim.Table.sql
dbo.OutpatientFact.Table.sql
dbo.OutpatientFinancialClassDim.Table.sql
dbo.PatientDim.Table.sql
dbo.PharmacyDim.Table.sql
dbo.PharmacyPhysicalTypeDim.Table.sql
dbo.ProcedureCategoryDim.Table.sql
dbo.ProcedureDim.Table.sql
dbo.ProcedureOrderClassDim.Table.sql
dbo.ProcedureOrderFact.Table.sql
dbo.ProcedureOrderModeDim.Table.sql
dbo.ProcedureOrderPriorityDim.Table.sql
dbo.ProcedureOrderSetDm.Table.sql
dbo.ProcedureOrderSourceDim.Table.sql
dbo.ProcedureOrderStandingStatusDim.Table.sql
dbo.ProcedureOrderStatusDim.Table.sql
dbo.ProcedureOrderTypeDim.Table.sql
dbo.ProcedureRevenueCodeDim.Table.sql
dbo.ProcedureTypeDim.Table.sql
dbo.ProgramDim.Table.sql
dbo.ProviderAffiliationDim.Table.sql
dbo.ProviderClinicianTitleDim.Table.sql
dbo.ProviderDim.Table.sql
dbo.ProviderFieldOfPracticeDim.Table.sql
dbo.ProviderInternalExternalDim.Table.sql
dbo.ProviderPrimaryDepartmentDim.Table.sql
dbo.ProviderPrimarySpecialtyDim.Table.sql
dbo.ProviderReportingStructureDim.Table.sql
dbo.ProviderTypeDim.Table.sql
dbo.SugicalProcedureEventWoundClassDim.Table.sql
dbo.SurgicalCaseClassDim.Table.sql
dbo.SurgicalCaseDim.Table.sql
dbo.SurgicalCaseFact.Table.sql
dbo.SurgicalCasePatientClassDim.Table.sql
dbo.SurgicalCasePrimaryAnesthesiaTypeDim.Table.sql
dbo.SurgicalCasePrimaryServiceDim.Table.sql
dbo.SurgicalCaseProcedureLevelDim.Table.sql
dbo.SurgicalCaseReasonNotPerformedDim.Table.sql
dbo.SurgicalProcedureEventAnesthesiaTypeDim.Table.sql
dbo.SurgicalProcedureEventFact.Table.sql
dbo.SurgicalProcedureEventLateralityDim.Table.sql
dbo.SurgicalProcedureEventProcedureSiteDim.Table.sql
dbo.SurgicalProcedureEventServiceDim.Table.sql
dbo.SurgicalSupplyDim.Table.sql
dbo.SurgicalSupplyManufacturerDim.Table.sql
dbo.SurgicalSupplyUseFact.Table.sql
dbo.SurgicalSupplyUseLogStatusDim.Table.sql
dbo.SurgicalSupplyUseORServiceDim.Table.sql
dbo.SurgicalSupplyVendorDim.Table.sql
dbo.tblCube_Data_Types.Table.sql
dbo.tblCube_Dimensions.Table.sql
dbo.tblCube_Dimension_Type.Table.sql
dbo.tblCube_Hierarchies.Table.sql
dbo.tblCube_Levels.Table.sql
dbo.tblCube_Measures.Table.sql
dbo.tblCube_Measure_Aggregator.Table.sql
dbo.tblCube_Measure_Groups.Table.sql
dbo.tblCube_Measure_Group_vs_Dimensions.Table.sql
dbo.tblCube_Usage_Between_Dimensions_And_Facts.Table.sql
dbo.tblExecSqlStatements_Results_TableType_V01.Table.sql
dbo.TimeDim.Table.sql
dbo.ufn_BOMONTH.UserDefinedFunction.sql
dbo.ufn_DateToUnixEpochTimestamp.UserDefinedFunction.sql
dbo.ufn_FindPrimaryKey.UserDefinedFunction.sql
dbo.UserDim.Table.sql
dbo.UserGenderDim.Table.sql
dbo.usp_BackupDatabase.StoredProcedure.sql
dbo.usp_Cube_Load_Metadata.StoredProcedure.sql
dbo.usp_DropAllForeignKeyConstraints.StoredProcedure.sql
dbo.usp_ExecSqlStatements.StoredProcedure.sql
dbo.usp_FixForeignKeys.StoredProcedure.sql
dbo.usp_FixForeignKeys_BetweenDimensions.StoredProcedure.sql
dbo.usp_FixForeignKeys_FactsDimensions.StoredProcedure.sql
dbo.usp_MeasureGenerator_GrowthFromSamePeriodPreviousYear.StoredProcedure.sql
dbo.usp_MeasureGenerator_PercentageOfTotal.StoredProcedure.sql
dbo.usp_MeasureGenerator_PercentageOfTotal_For_Sum.StoredProcedure.sql
dbo.usp_MeasureGenerator_TestQueries.StoredProcedure.sql
dbo.usp_PopulateDateDimension.StoredProcedure.sql
dbo.usp_PopulateDiagnosisHierarchy.StoredProcedure.sql
dbo.usp_PopulateTally.StoredProcedure.sql
dbo.usp_PopulateTimeDimension.StoredProcedure.sql
dbo.usp_PopulateUserGenderDim.StoredProcedure.sql
dbo.usp_TruncateAllTables.StoredProcedure.sql
dbo.WriteToFile.StoredProcedure.sql
util.Schema.sql
util.Tally.Table.sql
util.usp_FixData_DepartmentDim.StoredProcedure.sql
util.usp_FixData_LabTestFact.StoredProcedure.sql
util.usp_FixData_LDAP_Values.StoredProcedure.sql
util.usp_RolePermissions.StoredProcedure.sql
