copy nul > _output.txt
sqlcmd -S localhost -i carilion_dw.Database.sql >> _output.txt
sqlcmd -S localhost -i dbo.BinaryDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.CensusGeographicalAreaDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.CensusMeasureFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.CensusMeasureTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.CensusSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DateDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DepartmentDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DiagnosisBridge.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DiagnosisFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DiagnosisHierarchy.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DiagnosisPresentOnAdmitDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DiagnosisSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DM_Quality_Fact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DRGDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DRGFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DRGSeqDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.DRGTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitAcuityLevelDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitDispositionDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitFinancialClass.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EDVisitMeansOfArrivalDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterBillingClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterDepartmentDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterEncouterTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterLevelofCareDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterPatientStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncounterProductLineDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.EncouterBaseClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ExecSqlStatementsTableType.UserDefinedTableType.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientAdmitSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientAdmitTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientDischargeDestinationDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientDischargeDispositionDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.InpatientPatientClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentResultFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentResultFactLabStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentResultFactResultFlagDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentSubstrateDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabComponentTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestCancellationReasonDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestNameDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestOrderPriorityDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestOrderSourceTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestOrderTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestSpecimenSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestSpecimenTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LabTestVerificationStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LDAP_Dim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.LDAP_UserProvider_ReportingBridge.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureGroupDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureMDFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureMLFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureQDFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureQLFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MeasureSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationAdministrationActionDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationAdministrationFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationAdministrationRouteDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationDEAClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationFormDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderCalculatedDoseUnitDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderDoseUnitDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderFrequencyDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderModeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderPriorityDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderQuantityUnitDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderRouteDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderSetSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationOrderSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationPharmacologicalClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationPharmacologicalSubclassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.MedicationTherapeuticClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientAdmitConfStatrusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientAppointmentConfirmationStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientAppointmentStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientCancellationReasonDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.OutpatientFinancialClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.PatientDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.PharmacyDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.PharmacyPhysicalTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureCategoryDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderModeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderPriorityDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderSetDm.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderSourceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderStandingStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureOrderTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureRevenueCodeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProcedureTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProgramDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderAffiliationDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderClinicianTitleDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderFieldOfPracticeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderInternalExternalDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderPrimaryDepartmentDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderPrimarySpecialtyDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderReportingStructureDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.ProviderTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SugicalProcedureEventWoundClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCaseClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCaseDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCaseFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCasePatientClassDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCasePrimaryAnesthesiaTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCasePrimaryServiceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCaseProcedureLevelDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalCaseReasonNotPerformedDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalProcedureEventAnesthesiaTypeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalProcedureEventFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalProcedureEventLateralityDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalProcedureEventProcedureSiteDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalProcedureEventServiceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyManufacturerDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyUseFact.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyUseLogStatusDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyUseORServiceDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.SurgicalSupplyVendorDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Data_Types.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Dimensions.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Dimension_Type.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Hierarchies.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Levels.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Measures.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Measure_Aggregator.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Measure_Groups.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Measure_Group_vs_Dimensions.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblCube_Usage_Between_Dimensions_And_Facts.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.tblExecSqlStatements_Results_TableType_V01.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.TimeDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Data_Types.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Dimensions.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Dimension_Type.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Hierarchies.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Levels.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Measures.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Measure_Aggregator.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Measure_Groups.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Measure_Group_vs_Dimensions.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Usage_Between_Dimensions_And_Facts.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.Cube_Usage_Between_Dimensions_And_Facts__Excel_Compatible.View.sql >> _output.txt
sqlcmd -S localhost -i dbo.ufn_BOMONTH.UserDefinedFunction.sql >> _output.txt
sqlcmd -S localhost -i dbo.ufn_DateToUnixEpochTimestamp.UserDefinedFunction.sql >> _output.txt
sqlcmd -S localhost -i dbo.ufn_FindPrimaryKey.UserDefinedFunction.sql >> _output.txt
sqlcmd -S localhost -i dbo.UserDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.UserGenderDim.Table.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_ExecSqlStatements.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_BackupDatabase.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_Cube_Load_Metadata.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_DropAllForeignKeyConstraints.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_FixForeignKeys_BetweenDimensions.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_FixForeignKeys_FactsDimensions.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_FixForeignKeys.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_MeasureGenerator_GrowthFromSamePeriodPreviousYear.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_MeasureGenerator_PercentageOfTotal.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_MeasureGenerator_PercentageOfTotal_For_Sum.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_MeasureGenerator_TestQueries.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_PopulateDateDimension.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_PopulateDiagnosisHierarchy.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_PopulateTally.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_PopulateTimeDimension.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_PopulateUserGenderDim.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.usp_TruncateAllTables.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i dbo.WriteToFile.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i util.Schema.sql >> _output.txt
sqlcmd -S localhost -i util.Tally.Table.sql >> _output.txt
sqlcmd -S localhost -i util.usp_FixData_DepartmentDim.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i util.usp_FixData_LabTestFact.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i util.usp_FixData_LDAP_Values.StoredProcedure.sql >> _output.txt
sqlcmd -S localhost -i util.usp_RolePermissions.StoredProcedure.sql >> _output.txt
